### ISSUE TITLE
Add Twitch.Embed object as well

### ISSUE THREAD

**Issue by billygerhard** [frozencure/twitch-player#1]
- **I'm submitting a ...**
  [ ] bug report
  [x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**

Can you also add the newer Twitch.Embed object. That basically is an enhanced player, has the same options as player, but also has like the playback stats which shows stream delay, etc.

The usage is under the Embed Everything page: https://dev.twitch.tv/docs/embed/everything

**Comment by frozencure** [comment]
Thanks for the info, I didn't realize there was more interactive player functionality. I'll release a new version with the Embed feature soon.

**Comment by frozencure** [comment]
Fixed in v2.0.0

**Comment by billygerhard** [comment]
It looks like you missed almost all of the functions inside the Embed Everything JS.

![image](https://user-images.githubusercontent.com/2285204/95243539-c7bb3100-07de-11eb-8b53-1465655cd9ea.png)

**Comment by zoton2** [comment]
Just be aware some of the functions that were added are undocumented, but still nice to have them typed. For example I know the `getPlaybackStats` method was removed because they consider it "deprecated" for whatever reason as of earlier this year (see the changelog at https://dev.twitch.tv/docs/change-log).

**Comment by frozencure** [comment]
Thanks for the information, I'll include `undocumented` / `deprecated` tags to the documentation of the functions that are no longer supported.
